export default {
  CREATE_USER: "CREATE_USER",
  LOAD_USERS: "LOAD_USERS",
  GET_USER: "GET_USER",

  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  LOAD_CUSTOMERS: "LOAD_CUSTOMERS",
  GET_CUSTOMER: "GET_CUSTOMER",

  LOAD_ROLES: "LOAD_ROLES",
  CREATE_TRANSACTION: "CREATE_TRANSACTION",

  LOAD_ACCOUNTS: "LOAD_ACCOUNTS",
  LOCKED_ACCOUNT: "LOCKED_ACCOUNT",
  OPEN_ACCOUNT: "OPEN_ACCOUNT",

  LOAD_TRANSACTIONS: "LOAD_TRANSACTIONS"
};
