export default {
  CREATE_USER: "CREATE_USER",
  LOAD_USERS: "LOAD_USERS",
  GET_USER: "GET_USER",

  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  LOAD_CUSTOMERS: "LOAD_CUSTOMERS",
  GET_CUSTOMER: "GET_CUSTOMER",

  CREATE_TRANSACTION: "CREATE_TRANSACTION"
};
